[package]
authors     = ["DarkSky"]
description = "A minimp4 Rust binding"
edition     = "2021"
homepage    = "https://github.com/darkskygit/minimp4.rs"
include     = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]
keywords    = ["minimp4", "mp4", "muxer", "h264", "h265"]
license     = "MPL-2.0"
name        = "minimp4"
readme      = "README.md"
repository  = "https://github.com/darkskygit/minimp4.rs"
version     = "0.1.2"

[features]
aac     = ["fdk-aac-sys"]
default = []

[dependencies]
fdk-aac-sys = { version = "0.5.0", optional = true }
libc        = "0.2.155"
minimp4-sys = { path = "../minimp4-sys" }
